services:
  backend:
    build: ./RAG_quizz
    container_name: rag_backend
    ports:
      - "8000:8000"

    env_file:
      - ./RAG_quizz/.env

    environment:
      - HF_TOKEN=${HF_TOKEN}
      - HF_HUB_DISABLE_PROGRESS_BARS=0 
      - PYTHONUNBUFFERED=1
    # CẤU HÌNH CẤP QUYỀN TRUY CẬP GPU (NVIDIA CUDA)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


    volumes:
      - ./RAG_quizz/storage:/app/storage
      - ./RAG_quizz/data:/app/data
      - ./hf_cache:/root/.cache/huggingface 

  frontend:
    build: ./RAG_Frontend
    container_name: rag_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
